name: PR Delay Action

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  delay-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Simulate Workload
        run: |
          echo "Starting 2-minute wait..."
          sleep 120
          echo "Done waiting!"
